### ISSUE TITLE
thread 'main' panicked at src/main.rs:61:46

### ISSUE THREAD

**Issue by 0x241F31** [kvark/vandals-and-heroes#1]
```
called `Result::unwrap()` on an `Err` value: Format(FormatError { inner: InvalidSignature })
```

**Comment by kvark** [comment]
Interesting, thank you for giving it a shot! What OS is this?

**Comment by kvark** [comment]
I tested it. The problem is in LFS. You need to do `git lfs pull` in order to load those large images (for maps).
I added a note to README in commit 789b999bb0bbb1325300df13de26beb8c77e3380
